development:
  adapter: postgresql
  encoding: unicode
  database: barbarossa
  pool: 5
  username: prosa
  password: zaq12wsx

test:
  adapter: postgresql
  encoding: unicode
  database: barbarossa
  pool: 5
  username: prosa
  password: zaq12wsx

production:
  adapter: postgresql
  encoding: unicode
  database: barbarossa
  pool: 5
  username: prosa
  password: zaq12wsx
